# Generated by Django 4.2 on 2023-05-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unid', models.CharField(max_length=10)),
                ('qtde', models.IntegerField()),
                ('data', models.DateField()),
            ],
        ),
    ]
